### ISSUE TITLE
uLisp-ARM 4.0b is available

### ISSUE THREAD

**Issue by Megamemnon** [yarh-io/ulisp-arm-keyboard-featherwing#1]
I love his repo. Found it by accident and installed it on my keyboard featherwing with an M4 Express. I see this is based on uLisp for Arm version 3.4. Version 4 is now available. So I implemented your changes, but it isn't working. I'm going to try to figure out how to use this pull request thing to submit my code for comparison to yours.

**Comment by Megamemnon** [comment]
Compared my code to yours with the handy compare feature here on github, found the prob, fixed, tested, and submitted a PR.

**Comment by yarh-io** [comment]
Hi Megamemnon,

You did a great job! Thank you. This project is at a low priority for me at
the moment unfortunately. I'm planning to return to it in the new year, and
add some sort of "operating system", with ability to read/write/list lisp
files from/to the available media, like internal memory and SD cards. This
will make the device more like a real Lisp computer, I hope. :-)

Here is the housing I created for this project -

[image: IMG_5293.jpg]

Best regards,
SNC
